[project]
name = "sysguard-py"
version = "0.1.0"
description = "a simple system protection system using clanav where it does real-time scans and etc while still being simple on the system usage"
authors = [
    {name = "kiyo"}
]
license = "mit"
requires-python = ">=3.14"
dependencies = [
    "inotify-simple (>=2.0.1,<3.0.0)",
    "pathlib (>=1.0.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
